export const content = {
  en: {
    logo: "GaitFit AI",
    tagline: "Walk Smart. Wear Right.",
    heroSub: "AI-powered gait intelligence for better shoe decisions.",
    start: "Start Analysis",
    uploadTitle: "Upload Side-View Walking Video",
    uploadHint: "10 seconds max, 50MB max, barefoot walk preferred.",
    dropTitle: "Drop your video here or click to browse",
    dropSub: "Formats: MP4, MOV, M4V",
    analyze: "Analyze Gait",
    analyzing: "Analyzing Your Gait",
    working: "Processing...",
    step1: "Video + Pose Extraction",
    step2: "Feature + Model Classification",
    step3: "Recommendation Mapping",
    failedProcess: "Failed to process video.",
    retryUpload: "Try Another Upload",
    failTip1: "Use bright lighting and avoid shadows on legs/feet.",
    failTip2: "Keep the full body in frame with a stable camera.",
    failTip3: "Prefer a clean side-view walk for 8-10 seconds.",
    gaitReport: "Gait Insight Report",
    pronation: "Pronation",
    strike: "Strike Pattern",
    knee: "Knee Alignment",
    arch: "Arch Type",
    cadence: "Cadence",
    symmetry: "Symmetry",
    confidence: "Confidence",
    recs: "Top 3 Recommendations",
    visualTitle: "Visual Evidence",
    keyFramesTitle: "3 Key Gait Frames",
    frameLabel: "Frame",
    sideLabel: "Tracking Side",
    kneeAngle: "Knee Angle",
    ankleAngle: "Ankle Angle",
    quality: "Quality",
    left: "Left",
    right: "Right",
    stability: "Stability Shoes",
    motion_control: "Motion Control Shoes",
    cushioned: "Cushioned Shoes",
    neutral_running: "Neutral Running Shoes",
    back: "Analyze Another Video",
    downloadEvidence: "Download Image",
    downloadReport: "Download Report",
    downloadJson: "Download JSON",
    downloadPdf: "Download PDF",
    ourScience: "Our Science",
    testNow: "Test Yourself",
    landingKicker: "AI-Powered Gait Analysis",
    landingTitle: "See Your Movement. Improve Your Footwear Match.",
    landingSub: "Computer vision + biomechanics turns your walking video into practical shoe guidance in under a minute.",
    computerVision: "Computer Vision AI",
    computerVisionDesc: "Tracks key lower-body joints frame-by-frame to estimate gait mechanics with explainable visual evidence.",
    biomechanics: "Biomechanics Engine",
    biomechanicsDesc: "Measures ankle, knee, and symmetry metrics through stance phases to identify loading and stability patterns.",
    correctiveEngine: "Corrective Recommendation",
    correctiveEngineDesc: "Maps gait patterns to shoe categories and confidence scores with clear reasons you can act on.",
    howItWorks: "How It Works",
    stepUpload: "Upload your 10-second side-view walk",
    stepAnalyze: "We detect pose and compute gait features",
    stepRecommend: "Get evidence-backed shoe recommendations",
    scanTime: "Scan Time",
    visualDemo: "Live Motion Mapping",
    visualPoint1: "Lower-body joint tracking",
    visualPoint2: "Step event detection",
    visualPoint3: "Footwear category scoring",
    clickToFocus: "Click a key frame to focus it above",
    trendTitle: "Frame Quality Trend"
    ,
    contact: "Contact",
    links: "Links",
    address: "Address",
    contactPage: "Contact",
    contactIntro: "For collaborations, product demos, or partnership discussions, reach out below.",
    footerTagline: "AI-powered gait analysis and evidence-first footwear guidance."
  },
  hi: {
    logo: "GaitFit AI",
    tagline: "स्मार्ट चलें। सही जूते पहनें।",
    heroSub: "बेहतर जूता चुनने के लिए AI आधारित gait analysis।",
    start: "शुरू करें",
    uploadTitle: "साइड-व्यू वॉकिंग वीडियो अपलोड करें",
    uploadHint: "अधिकतम 10 सेकंड, 50MB, बेहतर परिणाम के लिए नंगे पैर चलें।",
    dropTitle: "वीडियो ड्रॉप करें या चुनने के लिए क्लिक करें",
    dropSub: "फॉर्मेट: MP4, MOV, M4V",
    analyze: "गेट विश्लेषण करें",
    analyzing: "आपकी चाल का विश्लेषण हो रहा है",
    working: "प्रोसेसिंग...",
    step1: "वीडियो और पोज़ एक्सट्रैक्शन",
    step2: "फीचर और मॉडल वर्गीकरण",
    step3: "रिकमेंडेशन मैपिंग",
    failedProcess: "वीडियो प्रोसेस नहीं हो पाई।",
    retryUpload: "फिर से अपलोड करें",
    failTip1: "अच्छी रोशनी रखें और पैरों/टांगों पर छाया न हो।",
    failTip2: "पूरा शरीर फ्रेम में रखें और कैमरा स्थिर रखें।",
    failTip3: "8-10 सेकंड का साफ साइड-व्यू वॉक वीडियो दें।",
    gaitReport: "गेट इनसाइट रिपोर्ट",
    pronation: "प्रोनेशन",
    strike: "फुट स्ट्राइक",
    knee: "घुटने का संरेखण",
    arch: "आर्च टाइप",
    cadence: "कडेंस",
    symmetry: "समरूपता",
    confidence: "विश्वास स्तर",
    recs: "टॉप 3 सुझाव",
    visualTitle: "विज़ुअल एविडेंस",
    keyFramesTitle: "3 प्रमुख गेट फ्रेम",
    frameLabel: "फ्रेम",
    sideLabel: "ट्रैकिंग साइड",
    kneeAngle: "घुटना कोण",
    ankleAngle: "एंकल कोण",
    quality: "गुणवत्ता",
    left: "बायां",
    right: "दायां",
    stability: "स्टेबिलिटी शूज़",
    motion_control: "मोशन कंट्रोल शूज़",
    cushioned: "कुशन्ड शूज़",
    neutral_running: "न्यूट्रल रनिंग शूज़",
    back: "नई वीडियो विश्लेषित करें",
    downloadEvidence: "इमेज डाउनलोड करें",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    downloadJson: "JSON डाउनलोड करें",
    downloadPdf: "PDF डाउनलोड करें",
    ourScience: "हमारा विज्ञान",
    testNow: "अभी टेस्ट करें",
    landingKicker: "AI आधारित गेट विश्लेषण",
    landingTitle: "अपनी चाल समझें। सही फुटवेयर चुनें।",
    landingSub: "कंप्यूटर विज़न और बायोमैकेनिक्स आपके वॉक वीडियो को 1 मिनट से कम समय में उपयोगी सुझाव में बदलते हैं।",
    computerVision: "कंप्यूटर विज़न AI",
    computerVisionDesc: "लोअर-बॉडी जॉइंट ट्रैकिंग से चाल का विज़ुअल और समझने योग्य विश्लेषण मिलता है।",
    biomechanics: "बायोमैकेनिक्स इंजन",
    biomechanicsDesc: "एंकल, घुटना और सिमेट्री मेट्रिक्स से लोडिंग और स्थिरता पैटर्न पता चलता है।",
    correctiveEngine: "करेक्टिव रिकमेंडेशन",
    correctiveEngineDesc: "गेट पैटर्न के आधार पर सही शू कैटेगरी और क्लियर कारण दिखते हैं।",
    howItWorks: "कैसे काम करता है",
    stepUpload: "10 सेकंड की साइड-व्यू वॉक वीडियो अपलोड करें",
    stepAnalyze: "हम पोज़ और गेट फीचर्स निकालते हैं",
    stepRecommend: "एविडेंस के साथ टॉप शू सुझाव पाएं",
    scanTime: "स्कैन समय",
    visualDemo: "लाइव मोशन मैपिंग",
    visualPoint1: "लोअर-बॉडी जॉइंट ट्रैकिंग",
    visualPoint2: "स्टेप इवेंट डिटेक्शन",
    visualPoint3: "फुटवेयर कैटेगरी स्कोरिंग",
    clickToFocus: "फोकस बदलने के लिए कोई key frame चुनें",
    trendTitle: "फ्रेम क्वालिटी ट्रेंड"
    ,
    contact: "संपर्क",
    links: "लिंक्स",
    address: "पता",
    contactPage: "संपर्क",
    contactIntro: "सहयोग, डेमो या पार्टनरशिप चर्चा के लिए नीचे दिए गए संपर्क का उपयोग करें।",
    footerTagline: "AI आधारित gait analysis और evidence-first footwear guidance."
  }
};
